SIM ?= icarus
TOPLEVEL_LANG ?= verilog
ROOT := $(abspath ..)
ASIC := $(ROOT)/asic_core/rtl

PROJECT_SOURCES := \
  $(ROOT)/src/tt_um_lfglabs_lsc1u.sv \
  $(ROOT)/src/lsc1u_core.sv \
  $(ASIC)/gf2n_mul_bitstream.sv \
  $(ASIC)/gf128_mul_bitstream.sv

ifeq ($(GATES),yes)
SIM_BUILD := sim_build/tt_gl
COMPILE_ARGS += -DGL_TEST -DFUNCTIONAL -DUSE_POWER_PINS -DSIM -DUNIT_DELAY=\#1
VERILOG_SOURCES += $(PDK_ROOT)/sky130A/libs.ref/sky130_fd_sc_hd/verilog/primitives.v
VERILOG_SOURCES += $(PDK_ROOT)/sky130A/libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v
VERILOG_SOURCES += $(CURDIR)/gate_level_netlist.v
else
SIM_BUILD := sim_build/tt_rtl
COMPILE_ARGS += -g2012 -Wall
VERILOG_SOURCES += $(PROJECT_SOURCES)
endif

VERILOG_SOURCES += $(CURDIR)/tt_tb.sv
TOPLEVEL := tt_tb
COCOTB_TEST_MODULES := test_tt
MODULE := test_tt
export PYTHONPATH := $(ROOT):$(PYTHONPATH)

include $(shell cocotb-config --makefiles)/Makefile.sim
