`timescale 1ns/1ps
`default_nettype none

module tb_stream_alu;
    reg clk = 1'b0;
    always #20 clk = ~clk; // 25 MHz

    reg rst_n = 1'b0;
    reg abort = 1'b0;
    reg [7:0] rx_data = 8'b0;
    reg rx_valid = 1'b0;
    wire rx_ready;
    wire [7:0] tx_data;
    wire tx_valid;
    reg tx_ready = 1'b1;
    wire busy;
    wire done_pulse;
    wire fault;

    reg [7:0] captured [0:63];
    integer capture_count = 0;
    integer i;

    leanvm_b_stream_alu dut (
        .clk(clk), .rst_n(rst_n), .abort(abort),
        .rx_data(rx_data), .rx_valid(rx_valid), .rx_ready(rx_ready),
        .tx_data(tx_data), .tx_valid(tx_valid), .tx_ready(tx_ready),
        .busy(busy), .done_pulse(done_pulse), .fault(fault)
    );

    always @(posedge clk) begin
        if (tx_valid && tx_ready) begin
            captured[capture_count] <= tx_data;
            capture_count <= capture_count + 1;
        end
    end

    task automatic send_byte(input [7:0] value);
        begin
            @(negedge clk);
            rx_data  = value;
            rx_valid = 1'b1;
            do @(posedge clk); while (!rx_ready);
            @(negedge clk);
            rx_valid = 1'b0;
        end
    endtask

    task automatic wait_outputs(input integer count);
        integer guard;
        begin
            guard = 0;
            while (capture_count < count) begin
                @(posedge clk);
                guard = guard + 1;
                if (guard > 1000)
                    $fatal(1, "timeout waiting for %0d output bytes", count);
            end
            @(posedge clk);
        end
    endtask

    task automatic expect_bytes(input integer n, input [127:0] expected);
        integer k;
        reg [7:0] expected_byte;
        begin
            wait_outputs(n);
            for (k = 0; k < n; k = k + 1) begin
                expected_byte = expected[k*8 +: 8];
                if (captured[k] !== expected_byte) begin
                    $display("byte mismatch index=%0d got=%02x expected=%02x",
                             k, captured[k], expected_byte);
                    $fatal(1);
                end
            end
        end
    endtask

    task automatic expect_word(input [127:0] expected);
        begin
            wait_outputs(16);
            for (i = 0; i < 16; i = i + 1)
                if (captured[i] !== expected[i * 8 +: 8])
                    $fatal(1, "byte %0d: expected %02x, got %02x", i,
                           expected[i * 8 +: 8], captured[i]);
        end
    endtask

    task automatic clear_capture;
        begin
            capture_count = 0;
            for (i = 0; i < 64; i = i + 1)
                captured[i] = 8'b0;
        end
    endtask

    reg [127:0] a;
    reg [127:0] b;
    reg [127:0] expected;

    initial begin
        repeat (3) @(posedge clk);
        rst_n = 1'b1;
        repeat (2) @(posedge clk);

        // XOR128, interleaved bytes.
        clear_capture();
        a = 128'h0123456789abcdef0011223344556677;
        b = 128'hfedcba9876543210ffeeddccbbaa9988;
        expected = a ^ b;
        send_byte(8'h01);
        for (i = 0; i < 16; i = i + 1) begin
            send_byte(a[i * 8 +: 8]);
            send_byte(b[i * 8 +: 8]);
        end
        expect_word(expected);

        // SET128 echo.
        clear_capture();
        a = 128'hffeeddccbbaa99887766554433221100;
        send_byte(8'h03);
        for (i = 0; i < 16; i = i + 1)
            send_byte(a[i * 8 +: 8]);
        expect_word(a);

        // NONZERO, both zero and nonzero.
        clear_capture();
        send_byte(8'h04);
        for (i = 0; i < 16; i = i + 1)
            send_byte(8'h00);
        wait_outputs(1);
        if (captured[0] !== 8'h00)
            $fatal(1, "zero test failed");

        clear_capture();
        send_byte(8'h04);
        for (i = 0; i < 16; i = i + 1)
            send_byte(i == 11 ? 8'h80 : 8'h00);
        wait_outputs(1);
        if (captured[0] !== 8'h01)
            $fatal(1, "nonzero test failed");

        // MUL128 random fixed vector, independently generated by polynomial reduction.
        clear_capture();
        a = 128'h0123456789abcdef0011223344556677;
        b = 128'hfedcba9876543210ffeeddccbbaa9988;
        expected = 128'h725dfbe1230caa91f6d9a29b1c334850;
        send_byte(8'h02);
        for (i = 0; i < 16; i = i + 1)
            send_byte(a[i * 8 +: 8]);
        for (i = 0; i < 16; i = i + 1)
            send_byte(b[i * 8 +: 8]);
        expect_word(expected);

        // Reduction boundary: x^127 * x = 0x87.
        clear_capture();
        a = 128'h80000000000000000000000000000000;
        b = 128'h00000000000000000000000000000002;
        expected = 128'h00000000000000000000000000000087;
        send_byte(8'h02);
        for (i = 0; i < 16; i = i + 1)
            send_byte(a[i * 8 +: 8]);
        for (i = 0; i < 16; i = i + 1)
            send_byte(b[i * 8 +: 8]);
        expect_word(expected);

        if (fault)
            $fatal(1, "unexpected sticky fault");

        $display("PASS: leanVM-b MinCore stream ALU");
        $finish;
    end
endmodule

`default_nettype wire
